spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vorxer/transistorzone-config
          default-label: master
          search-paths:
            - '*service'
server:
  port: 8200
