spring:
  application:
    name: user-service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: info
